package vistas;

import javax.swing.WindowConstants;

public class Cliente extends javax.swing.JFrame {

    String user, nombre_usuario;
    public static int sesion_usuario;
    public Cliente() {
        initComponents();
        user = LoginFrame.user;
        sesion_usuario = 1;
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonReserva = new javax.swing.JButton();
        ButtonFactura = new javax.swing.JButton();
        ButtonProductos2 = new javax.swing.JButton();
        ButtonProductos3 = new javax.swing.JButton();
        ButtonFactura1 = new javax.swing.JButton();
        PanelHeader = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        PanelMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(108, 188, 172));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("CLIENTE");

        ButtonReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/Boton-bar-reservas.png"))); // NOI18N
        ButtonReserva.setBorder(null);
        ButtonReserva.setContentAreaFilled(false);
        ButtonReserva.setFocusPainted(false);
        ButtonReserva.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/BotonPress-bar-reservas.png"))); // NOI18N
        ButtonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReservaActionPerformed(evt);
            }
        });

        ButtonFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/Boton-bar-facturas.png"))); // NOI18N
        ButtonFactura.setBorder(null);
        ButtonFactura.setContentAreaFilled(false);
        ButtonFactura.setFocusPainted(false);
        ButtonFactura.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/BotonPress-bar-facturas.png"))); // NOI18N
        ButtonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFacturaActionPerformed(evt);
            }
        });

        ButtonProductos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/Boton-bar-Pedidos.png"))); // NOI18N
        ButtonProductos2.setBorder(null);
        ButtonProductos2.setContentAreaFilled(false);
        ButtonProductos2.setFocusPainted(false);
        ButtonProductos2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/Boton-Press-Pedidos.png"))); // NOI18N
        ButtonProductos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProductos2ActionPerformed(evt);
            }
        });

        ButtonProductos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/Boton-bar-Productos.png"))); // NOI18N
        ButtonProductos3.setBorder(null);
        ButtonProductos3.setContentAreaFilled(false);
        ButtonProductos3.setFocusPainted(false);
        ButtonProductos3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/BotonPress-bar-productos.png"))); // NOI18N
        ButtonProductos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProductos3ActionPerformed(evt);
            }
        });

        ButtonFactura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/Boton-Contacto.png"))); // NOI18N
        ButtonFactura1.setBorder(null);
        ButtonFactura1.setContentAreaFilled(false);
        ButtonFactura1.setFocusPainted(false);
        ButtonFactura1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/Press-Contacto.png"))); // NOI18N
        ButtonFactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFactura1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonProductos3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(ButtonProductos3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(ButtonProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(ButtonReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ButtonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ButtonFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 910));

        PanelHeader.setBackground(new java.awt.Color(33, 45, 62));

        lbTitulo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("Principal");

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1038, Short.MAX_VALUE))
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(PanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1320, -1));

        PanelMain.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 1320, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReservaActionPerformed
        // TODO add your handling code here:
        lbTitulo.setText("Reservas");
        PanelReservaCliente panelReserva= new PanelReservaCliente();
        PanelMain.add(panelReserva);
    }//GEN-LAST:event_ButtonReservaActionPerformed

    private void ButtonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFacturaActionPerformed
        // TODO add your handling code here:
        lbTitulo.setText("Facturas");
        PanelFacturasCliente panelFactura= new PanelFacturasCliente();
        PanelMain.add(panelFactura);
    }//GEN-LAST:event_ButtonFacturaActionPerformed

    private void ButtonProductos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProductos2ActionPerformed
        // TODO add your handling code here:
        lbTitulo.setText("Pedidos");
        PanelPedidosCliente panelPedidos = new PanelPedidosCliente();
        PanelMain.add(panelPedidos);
    }//GEN-LAST:event_ButtonProductos2ActionPerformed

    private void ButtonProductos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProductos3ActionPerformed
        lbTitulo.setText("Producto");
        PanelProductosCliente panelProducto = new PanelProductosCliente();
        PanelMain.add(panelProducto);
        
    }//GEN-LAST:event_ButtonProductos3ActionPerformed

    private void ButtonFactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFactura1ActionPerformed
        // TODO add your handling code here:
        lbTitulo.setText("Contacto");
        PanelContacto panelContacto = new PanelContacto();
         PanelMain.add(panelContacto);
    }//GEN-LAST:event_ButtonFactura1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonFactura;
    private javax.swing.JButton ButtonFactura1;
    private javax.swing.JButton ButtonProductos2;
    private javax.swing.JButton ButtonProductos3;
    private javax.swing.JButton ButtonReserva;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
